Update TEST

diff --git a/Jenkins/TEST b/Jenkins/TEST
--- a/Jenkins/TEST
+++ b/Jenkins/TEST
@@ -1,1 +1,12 @@
-df
+echo "--------------Test Started-----------------"
+result=`grep "Hello" index.html | wc -l`
+echo $result
+if [ "$result" = "1" ]
+then 
+    echo "Test Passed"
+else
+    echo "Test Failed"
+    exit 1
+fi
+
+echo "--------------Test Finished-----------------"
